included:
  - RestaurantSearch
  - RestaurantSearchTests
opt_in_rules: # デフォルト無効のルールのうち、有効にするもの。
  - empty_count
  - file_header
  - explicit_init
  - closure_spacing
  - overridden_super_call
  - redundant_nil_coalescing
  - private_outlet
  - nimble_operator
  - attributes
  - operator_usage_whitespace
  - closure_end_indentation
  - first_where
  - sorted_imports
  - number_separator
  - prohibited_super_call
  - fatal_error_message
  
disabled_rules: # 無効にするルール
  - trailing_whitespace
  - file_header
  - sorted_imports
  - nesting
  - force_cast
  - object_literal

line_length: 200
number_separator:
  minimum_length: 5