coverage:
  status:	  status:
    project:	    project:
      default:	      default:
        # basic	        # basic
        target: auto	        target: number 0%
        threshold: 0%	        threshold: null
        base: auto 
        # advanced
        branches: null
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: false
        flags: null
        paths: null
